---
- hosts: WebServer
  become: yes
  tasks:
  - name: install tomcat
    apt:
      name: tomcat7
      state: present
- hosts: Ubuntu
  become: yes
  tasks:
  - name: install 
    apt:
      name: nodejs
      state: present
