---
- hosts: WebServer
  become: yes
  tasks:
  - name: install packer
    apt:
      name: packer
      state: present
- hosts: Ubuntu
  become: yes
  tasks:
  - name: install 
    apt:
      name: nodejs
      state: present
